### ISSUE TITLE
Extend VmValue operations to support arrays up to 256 items

### ISSUE THREAD

**Issue by iNemesis21** [purpleprotocol/purple_prototype#143]
Right now the operations implemented for VmValue supports array with a maximum of 8 items, but we should support arrays up to 256 items.

**Comment by octavonce** [comment]
@iNemesis21 This should be handled in #141?

**Comment by iNemesis21** [comment]
@octavonce when the required changes from #141 will be resolved there will be also other operations which will remain with the same problem. This bug should handle the other part, so no other fixes will be included among the implementation of the issue solved in #141. If you consider I can include everything in #141.

**Comment by octavonce** [comment]
@iNemesis21 Yeah that's fair enough. Then as long as this is documented, I am fine either way. You can include this in #141 or leave it for another PR if you wish.
