### ISSUE TITLE
Send transaction validation

### ISSUE THREAD

**Issue by octavonce** [purpleprotocol/purple_prototype#2]
A `Send` transaction sends funds from a sender address to a receiving address. The validation logic for a `Send` transaction must do the following:

- Check that the sender address exists.
- Check that the sender address has the amount listed to be sent. 
- Check that the sender address has the amount listed to be paid as the transaction's fee.
- If the transaction's fee is paid in the same currency as the one being transferred, check that the sender address has the summed amounts.
- In case the receiver address is either a shareholder, multi-signature or contract address, check if the account is listed in the ledger.

Note: `Burn` validation logic can serve as an example.

**Comment by multisme** [comment]
- Check if the account exist if the  receiver is a shareholder account.

**Comment by octavonce** [comment]
Updated main issue

**Comment by octavonce** [comment]
Closed in favor of #20.
